CREATE TABLE `member` (
  `memberID` int NOT NULL,
  `name` varchar(45) NOT NULL,
  `position` varchar(45) NOT NULL,
  `address` int NOT NULL,
  `age` int NOT NULL,
  `citizenship` varchar(45) NOT NULL,
  `country` varchar(45) NOT NULL,
  `state` varchar(45) NOT NULL,
  `county` varchar(45) NOT NULL,
  `tribe` varchar(45) DEFAULT NULL,
  `region` varchar(45) NOT NULL,
  `dob` date NOT NULL,
  `datejoined` date NOT NULL,
  `universityjoined` varchar(45) NOT NULL,
  `degree` varchar(45) NOT NULL,
  `veteranstatus` varchar(45) DEFAULT NULL,
  `martialstatus` varchar(45) NOT NULL,
  `citychapter` varchar(45) NOT NULL,
  `submember` varchar(45) NOT NULL,
  `representativeworker` tinyint NOT NULL,
  `chaptercoordinator` varchar(45) NOT NULL,
  PRIMARY KEY (`memberID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
