INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `tribe`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `veteranstatus`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0001', 'Bill Burr', 'member', '284 Line Lane OK', '47', 'Yes', 'US', 'OK', 'Tulsa', 'Chicotah', '5', '1973-04-28', '2009', 'Oklahoma State University', 'Finance ', '', 'Married', 'Tulsa Chapter', 'Student', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `tribe`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `veteranstatus`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0002', 'Maggie Williams', 'member', '849 Green Road TX', '34', 'Yes', 'US', 'TX', 'Fort Worth', '', '5', '1986-07-01', '2002', 'Texas A&M University', 'Mechanical Engineering', 'administratively discharged', 'Single', 'Dallas Chapter', 'Veteran', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `tribe`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0003', 'Bo Jen', 'member', '834 Goog Rd CA', '21', 'yes', 'US', 'CA', 'Santa Clara', '', '6', '1998-02-28', '2005', 'California State University', 'Engineering', 'Single ', 'Santa Clara Chapter', 'Student', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `tribe`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0004', 'Milton James', 'Vice President', '327 Mall Rd TX', '34', 'yes', 'US', 'TX', 'Tarrant', '', '5', '1986-05-05', '2010', 'Oklahoma State University', 'Electrical Engineering', 'single', 'Tarant Chapter', 'Student', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0005', 'Jo Fo', 'Tresurer', '421 Rockwall Ln NY', '48', 'yes', 'US', 'NY', 'Albany', '1', '1972-06-17', '2012', 'California State University', 'Computer Science', 'married', 'Albany Chapter', 'General', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `tribe`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `veteranstatus`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0006', 'Pete Mike', 'member', '639 Reckle St MI', '54', 'yes', 'US', 'MI', 'Oakland', '', '1', '1966-10-12', '2008', 'Oklahoma University', 'Computer Science', 'Career Veteran', 'married', 'Oakland Chapter', 'Veteran', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `tribe`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `veteranstatus`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0007', 'Jim Halpert', 'member', '1234 Shep St NB', '42', 'yes', 'US', 'NB', 'Douglas', '', '2', '1978-12-30', '2004', 'New York University', 'Electrical Engineering', '', 'divorced', 'Albany Chapter', 'Student', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `veteranstatus`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0008', 'Pam Beasley', 'Treasurer', '1314 Hill Crest Ln CA', '34', 'yes', 'US', 'CA', 'San Francisco', '6', '1986-01-05', '2014', 'Michigan State University', 'Computer Science- Information Systems', 'Medically Retired', 'single', 'San Francisco Chapter', 'Veteran', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0009', 'Michael Scott', 'member', '336 Woo Ln TX ', '38', 'yes', 'US', 'TX', 'Hunt', '5', '1982-06-14', '2014', 'University of Texas -Dallas', 'Information Technology', 'single', 'Dallas Chapter', 'General', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `tribe`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `veteranstatus`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0010', 'Jan Levingston', 'member', '224 Meat St GA', '31', 'yes', 'US', 'GA', 'Cherkee', '', '2', '1989-04-17', '2011', 'University of Arkansas', 'Engineering', 'Medically Retired', 'married', 'Atlanta Chapter', 'Veteran', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `tribe`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0011', 'Lisa Ham', 'member', '825 Will Ln TX', '28', 'yes', 'US', 'TX', 'Dallas', '', '5', '1992-03-12', '2012', 'Baylor University', 'Math', 'married', 'Dallas Chapter', 'Women', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0012', 'Gordon Guol', 'member', '624 Easy St NY', '34', 'yes', 'US', 'NY', 'Bronx', '1', '1986-09-10', '2011', 'Harvard University', 'Electrical Engineering ', 'married', 'Albany Chapter', 'General', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0013', 'Rainni Ron', 'member', '123 Street Ln TX', '33', 'yes', 'US', 'TX', 'Hunt', '5', '1987-05-09', '2012', 'Texas A&M University - Commerce', 'Computer Science', 'single', 'Dallas Chapter', 'Women', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `tribe`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `veteranstatus`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0014', 'Gill Samson', 'member', '872 Jillian St GA', '29', 'yes', 'US', 'GA', 'Fulton', '', '2', '1990-11-02', '2017', 'Baylor University', 'Information Technology', 'Career Veteran', 'married ', 'Dallas Chapter', 'Veteran', '0', '0');
INSERT INTO `chapters`.`member` (`memberID`, `name`, `position`, `address`, `age`, `citizenship`, `country`, `state`, `county`, `region`, `dob`, `yearjoined`, `universityjoined`, `degree`, `martialstatus`, `citychapter`, `submember`, `representativeworker`, `chaptercoordinator`) VALUES ('0015', 'May Rose', 'Treasurer', '435 Bilbo Lane NB', '27', 'yes', 'US', 'NB', 'Sarpy', '2', '1993-02-04', '2015', 'University of Texas - Dallas', 'Computer Science', 'single', 'Dallas Chapter', 'General', '0', '0');

